### ISSUE TITLE
Inner html insertion missing sanitization

### ISSUE THREAD

**Issue by brunokiafuka** [sduduzog/zatechradio#3]
### Description 
I've identified that we use `dangerouslySetInnerHTML` [here](https://github.com/sduduzog/zatechradio/blob/bf74ca82dedfd2c9d21ae016bfec3d4a915f307e/src/pages/%5Bepisode%5D.jsx#L54) it's use has no wrong implications but as best practice it is important to sanitize the HTML being injected, to ensure no unwanted script is being added. 

### Possible fix 

Use [DOMPurify](https://github.com/cure53/DOMPurify) to sanitize the HTML.

```js
// Original
lorem <b onmouseover="alert('mouseover');">ipsum</b>

// Sanitized
lorem <b>ipsum</b>
```

**Comment by vutlhari** [comment]
> ### Description
> I've identified that we use `dangerouslySetInnerHTML` [here](https://github.com/sduduzog/zatechradio/blob/bf74ca82dedfd2c9d21ae016bfec3d4a915f307e/src/pages/%5Bepisode%5D.jsx#L54) it's use has no wrong implications but as best practice it is important to sanitize the HTML being injected, to ensure no unwanted script is being added.
> 
> ### Possible fix
> Use [DOMPurify](https://github.com/cure53/DOMPurify) to sanitize the HTML.
> 
> ```js
> // Original
> lorem <b onmouseover="alert('mouseover');">ipsum</b>
> 
> // Sanitized
> lorem <b>ipsum</b>
> ```

I'm not a big fan of *adding a library willy-nilly*, I would suggest solving the problem without introducing a package. One could use regex.

**Comment by brunokiafuka** [comment]
> > ### Description
> 
> > I've identified that we use `dangerouslySetInnerHTML` [here](https://github.com/sduduzog/zatechradio/blob/bf74ca82dedfd2c9d21ae016bfec3d4a915f307e/src/pages/%5Bepisode%5D.jsx#L54) it's use has no wrong implications but as best practice it is important to sanitize the HTML being injected, to ensure no unwanted script is being added.
> 
> > 
> 
> > ### Possible fix
> 
> > Use [DOMPurify](https://github.com/cure53/DOMPurify) to sanitize the HTML.
> 
> > 
> 
> > ```js
> 
> > // Original
> 
> > lorem <b onmouseover="alert('mouseover');">ipsum</b>
> 
> > 
> 
> > // Sanitized
> 
> > lorem <b>ipsum</b>
> 
> > ```
> 
> 
> 
> I'm not a big fan of *adding a library willy-nilly*, I would suggest solving the problem without introducing a package. One could use regex.

Regex would be a good approach but it can easily miss a few edge cases. i.e: unwilling remove some hyperlinks. 

The suggest lib addresses multiple edge cases and is well maintained. Yet we can go with the Regex approach if simpler and less time consuming.

**Comment by vutlhari** [comment]
> > > ### Description
> > 
> > 
> > > I've identified that we use `dangerouslySetInnerHTML` [here](https://github.com/sduduzog/zatechradio/blob/bf74ca82dedfd2c9d21ae016bfec3d4a915f307e/src/pages/%5Bepisode%5D.jsx#L54) it's use has no wrong implications but as best practice it is important to sanitize the HTML being injected, to ensure no unwanted script is being added.
> > 
> > 
> > > 
> > 
> > 
> > > ### Possible fix
> > 
> > 
> > > Use [DOMPurify](https://github.com/cure53/DOMPurify) to sanitize the HTML.
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > // Original
> > 
> > 
> > > lorem ipsum
> > 
> > 
> > > 
> > 
> > 
> > > // Sanitized
> > 
> > 
> > > lorem ipsum
> > 
> > 
> > > 
> > 
> > 
> > I'm not a big fan of _adding a library willy-nilly_, I would suggest solving the problem without introducing a package. One could use regex.
> 
> Regex would be a good approach but it can easily miss a few edge cases. i.e: unwilling remove some hyperlinks.
> 
> The suggest lib addresses multiple edge cases and is well maintained. Yet we can go with the Regex approach if simpler and less time consuming.

That's an opportunity to add ✨**TESTS**✨

**Comment by vutlhari** [comment]
@sduduzog happy for this PR to go in - for now. But I'm gonna create an issue to remove [DOMPurify](https://github.com/cure53/DOMPurify)

**Comment by sduduzog** [comment]
@Vutlhari merged. Forgot to auto-close this issue

**Comment by brunokiafuka** [comment]
@sduduzog We only addressed it one place there's another component that also injects HTML without cleaning it up. A quick PR, maybe we could consider doing like util function that cleans the inject HTML and using the approach suggested by @Vutlhari

[missed file](https://github.com/sduduzog/zatechradio/blob/bf74ca82dedfd2c9d21ae016bfec3d4a915f307e/src/pages/%5Bepisode%5D.jsx#L54)

**Comment by sduduzog** [comment]
@brunokiafuka That's actual a dead component, which is better off being deleted altogether. The API that feeds the site does not provide episode details, so there's no episode details thus no episode id. The link to that route was supposed to be next to the listen button on the home screen but of course had to be removed

**Comment by brunokiafuka** [comment]
> @brunokiafuka That's actual a dead component, which is better off being deleted altogether. The API that feeds the site does not provide episode details, so there's no episode details thus no episode id. The link to that route was supposed to be next to the listen button on the home screen but of course had to be removed

🪦🪦🪦 R I P
