### ISSUE TITLE
NextSeo is not defined

### ISSUE THREAD

**Issue by mpendulo-dev** [sduduzog/zatechradio#6]
I cloned the project locally and I got the **NextSeo is not defined error** when I ran it:
![nextseo bug](https://user-images.githubusercontent.com/79789895/228508453-e7ef0f7e-3ee2-4c53-b6ad-654debaacfb1.png)

Solution:
- Imported NextSeo on the pages index
`import { NextSeo } from 'next-seo';`

**Comment by sduduzog** [comment]
@mpendulo-dev I reopened, fix is not yet on main branch but the pr, github will autoclose when the pull request is merged

**Comment by mpendulo-dev** [comment]
Alright, will check it out once it's merged.

**Comment by sduduzog** [comment]
merging now actually
